language: python

python:
  - '3.5'
  - '3.6'
  - 3.7-dev
  - nightly

matrix:
  allow_failures:
    - python: 3.7-dev
    - python: nightly

install:
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/requirements_dev.txt

script:
  - python setup.py flake8
  - python setup.py test
  - python setup.py sdist
  - python setup.py bdist_wheel

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: Ovv
  password:
    secure: sqi9AaRrIcLIZ7P90VkwVN2P8MfDm2WY5Z1J89QWFP3/kCxIWPRpFsOjHH4s3CO85IfpY77UNOOYHKnsI+A6FkodzyEAGqF8Eoe6QH0CXauSks7mJ7wjlKM93YYIZ3PkNkl/t4KFhBBpy845clkKFEJgc2TxG9DIA37rbrNHRXzqFIXrLtD/gUitokZnpTaJTFcbpb4V3NxEr5SnVP1vUf+Kz80aq/BJqwuNE+oJwDWtwxSC7zoqHRdG/MBYzBUNYjIBCzgwdRyGGREVCQhjaSLeg3pHmveXb9kFBaYH87ioJ+/uOuw2uNAlNpg1XasHgBhm4lFRQGhmm0eabIAZ6avRqSsIVpdzaLC5k3FkFJD6bFaIdAfpHZKPpipk6M7a/3YEQU8Ld3B+zk/6k3RT2cTGBKQfBuNKAy7yg1Ph6Vg+Dva820IwmWkz3PhDfeFzlXw6q28Mzb0bMU3KCA1E/n3mIrF4W6OX8eKunE7TzoMenZWRxsx3Sn78nMD4d/Uwaft5LswyrsItD9X0StigD27RminjjeEgeLd3Kx4yDSPNfIMw+qm1GilrgLZzezOhRV6KSQ1ugea+JAL3cZSsizxMiP9NhviaLPl49t59YDAlhBdsaAhxuNQV5JhVtr6uwc6WRrQHRbpvLveY+AYTsl+OAaYKjksQemD168s+26Y=
  on:
    repo: pyslackers/sirbot-plugins
    branch: master
    python: '3.6'
    tags: true
