language: python

python:
  - '3.5'
  - '3.6'
  - 3.7-dev
  - nightly

matrix:
  allow_failures:
    - python: 3.7-dev
    - python: nightly

install:
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/requirements_dev.txt

script:
  - python setup.py flake8
  - python setup.py test
  - python setup.py sdist
  - python setup.py bdist_wheel

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: Ovv
  password:
    secure: DdTynt+3zUDb9ZRmGSI5DSscxLm6495ECZQBiAPwzviyXVYvspe6L1cx9XRJpmXV6RUGR4qKhMP/0q7tPs6aXDmC+rYMX1Nr6mvXaZSxAmnkVz+tOy4LCvdOFR94Rr23A0QiqWiIdR+2C7d4qahxBTowtphBkUEnJ7Fxk9Foi8pcgrBy2IJApwNlRzoOtIc1HrwU+FWWzOLssn32tmEUtdoQLgI/E9bycHD0J+nH7XY2JfsVpq6s11PVBxkAguRN7H5uGO+UcgaX4TkErjYJZBMuWPvA/sz6hKBnQOEu2MEsAyR0gqq2NsfIgQc5meM2On1DZ3JMc7jusWRhDti3+xTMy9cQDnG+3E7CuscI/1j4oHtazDSCETXe/ept2q+ZhFTYh+s6SoKvCKflVw04yf75xTf/NJ7tf4/eseVtQd0/NF0MfTmqmubz5OyJGQuKwy1xp0tYkMF6tWGkaA5naPaD/4znDQQ/yodI9fr7bl9CTLYmeyu9DxUtF45GZBZq1UK43v2IwJYXuvJ3LkElyCHEdY+29V6Rx+3lFO9skH151zZfJd3nx58b907+0c9P5hHkbJ8SIuOiFDlugwN7DWnLzkc5BlHK72Qy2jSDpIMXryaWijf7HgCGMzKxqcYm3pQQ6CH0rSO2esHEB4iVnygEmroIUy+pm0XdCAf8M+A=
  on:
    repo: pyslackers/sirbot-plugins
    branch: master
    python: '3.6'
    tags: true
