language: python

python:
  - '3.6'
  - 3.7-dev
  - nightly

matrix:
  allow_failures:
    - python: 3.7-dev
    - python: nightly

install:
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/requirements_dev.txt

script:
  - python setup.py flake8
  - python setup.py test
  - python setup.py sdist
  - python setup.py bdist_wheel

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: Ovv
  password:
    secure: Wefhp2XKpxfo4hLTAmdRYEK68pTYhKx/prCD4gnWdueq37RpPPtlA7vMe3pla+k56fcBJ5ZAhnTLhCK6tiGIREFF/VqmL9p7KXMCLqNomeQxCCzEBENh6w8r90Vnxj4glH8Seh5ykX0ia4+PTndLVhvi7ayFOmxNokHXxB8EyaoR++cXlzODO6xmxMduWih1km5f6CkxWSFUF/Sz/Jkl+QUDLsUsPhUE8MDKjIWp6CFsB5xlM2IqahG7RuoL+URWifvwzPK0WfcqFfd2e/PykK5VZw4ki7hvJaWrcDeUoY/THXTY4uHmYEG0dQ99ga/GY3P6Y/gzBMpCfMKN8oJzHXym8mqLCqe2ZFZjEJ5FyeiGR6wcjhlyIzc+OWNt8fAL9+NWw99NDFmor4VnfkhXmU74LnvasdSxi2aaLx2KHqVnF82aBKwyfFIwccrw1HYzFf6j8QrE3vpC8UhMLDzKKXJAUC5AWFZCfl0tZg0/0jWOIVgB2rI1f6nAQwsFvXi5Bvigkewd82IdrfUkMjTjcu4CSO1Nqj/PqeTg5UhTNlTnxxdTIVre3/5kxJih5cZn5ywk4o3GP05NAcKx2Gek1uohcj16UjRIlVcU3NP82HNekPX5Q+w0k7DoycwR10C5JqRceDrumjOD8vhN4Ho/A5QwOlyUXxYwnMDRa8Zrvfg=
  on:
    repo: pyslackers/sirbot-plugins
    branch: master
    python: '3.6'
    tags: true
